name = "Fish"
version = "0.0.9"
authors = ["Hasit Mistry <hasitnm@gmail.com>"]
description = "Fish language support for Zed"
repository = "https://github.com/hasit/zed-fish"
id = "fish"
schema_version = 1

[languages]
Fish = "languages/fish"

[grammars]
fish = "grammars/fish.wasm"
grammar = "fish"
[grammars.fish]
repository = "https://github.com/ram02z/tree-sitter-fish"
commit = "a78aef9abc395c600c38a037ac779afc7e3cc9e0"
