name = "Fish"
grammar = "fish"
path_suffixes = ["fish"]
first_line_pattern = "^#!.*\\bfish\\b"
line_comments = ["# "]
brackets = [
    { start = "{", end = "}", close = false, newline = false },
    { start = "[", end = "]", close = false, newline = false },
    { start = "(", end = ")", close = false, newline = false },
]
